name: Publish to GitHub Pages

on:
  [push]

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - run: yarn install
      - name: Build Eleventy
        run: yarn build 
        env:
          REPO_URL: https://github.com/goliveira/eleventy-base-blog/
          WEB_ROOT_URL: https://goliveira.github.io/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./public
          publish_branch: gh-pages